### ISSUE TITLE
Improving the performance of FastReflection

### ISSUE THREAD

**Issue by jhgbrt** [jhgbrt/yadal#2]

**Comment by deipax** [comment]
I added an experimental version of FastReflection along with a sample unit tests to help with testing it.

The first thing I did is change how the getters/setters are accessed, I use FastReflection-T-.Instance.GetSetters().  The benefit of using that syntax is that no dictionary look up is needed in order to fetch accessors, it just returns them (IReadOnlyDictionary so they can not be changed by a careless user).

Note that I do not return the delegate directly but ISetter-T- and IGetter-T- along with helper methods on FastReflection-T- to access them either by name or expression syntax.  Expression syntax is nice in that it provides a compile time check for the user.  If a name on your POCO changes, your code will break.

The next thing I did was to use compiled expressions for my delegates instead of anon delegates.  They are slightly faster in execution, but not by much.  Initialization time is also slightly faster but since the price is paid only once, it is not a big deal.  This change was most due to my personal preference.

The next thing I did was add support for getting/setting fields.  During my work with fields, I noticed that field access is faster than property access.  To access a field only required about 1/2 time required to access a property (use a good profiler).  After looking into it, I verified that there is over head to accessing properties but I also found that automatic properties have a compiler generated field behind it.  As a result, if a property has a backing field, I use it.  Again, I added a sample unit tests to display this change and while using a simple stop watch will show the difference, the best method is to use a profiler.

Play with it, let me know what you think or if you have any questions.
